# Generated by Django 3.2.18 on 2023-04-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Report',
        ),
    ]
