# Generated by Django 3.2.18 on 2023-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0002_delete_book_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pos', models.FloatField()),
                ('neu', models.FloatField()),
                ('neg', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
