# Generated by Django 3.2.18 on 2023-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='senti',
            field=models.TextField(null=True),
        ),
    ]
